name: V2Ray Config Checker

on:
  schedule:
    - cron: '*/30 * * * *'  # Jalankan setiap 30 menit
  workflow_dispatch:

jobs:
  check-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        env:
          SUB_URL: ${{ secrets.SUB_URL }}
        run: |
          echo "Menjalankan checker.py dengan timeout 300 detik"
          timeout 300 python checker.py || echo "Script timeout atau gagal"

      - name: Commit and push Xray + results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add bin/xray active_configs.txt
          git commit -m "Update Xray binary + active configs" || echo "No changes to commit"
          git push origin main
